# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
from collections.abc import AsyncIterator
from datetime import datetime
from typing import Any
from typing import Callable
from typing import Generator
from unittest.mock import AsyncMock
from uuid import UUID
from uuid import uuid4

import pytest
from fastapi import FastAPI
from httpx import AsyncClient
from pydantic import SecretStr
from pytest import MonkeyPatch

from os2sync_export.autogenerated_graphql_client import GraphQLClient
from os2sync_export.autogenerated_graphql_client import (
    TestingEmployeeCreateEmployeeCreate,
)
from os2sync_export.autogenerated_graphql_client import (
    TestingEngagementCreateEngagementCreate,
)
from os2sync_export.autogenerated_graphql_client import (
    TestingOrgUnitCreateOrgUnitCreate,
)
from os2sync_export.autogenerated_graphql_client.input_types import ClassCreateInput
from os2sync_export.autogenerated_graphql_client.input_types import EmployeeCreateInput
from os2sync_export.autogenerated_graphql_client.input_types import (
    EngagementCreateInput,
)
from os2sync_export.autogenerated_graphql_client.input_types import FacetCreateInput
from os2sync_export.autogenerated_graphql_client.input_types import ITSystemCreateInput
from os2sync_export.autogenerated_graphql_client.input_types import (
    OrganisationUnitCreateInput,
)
from os2sync_export.autogenerated_graphql_client.input_types import RAValidityInput
from os2sync_export.autogenerated_graphql_client.input_types import ValidityInput
from os2sync_export.config import AMQPConnectionSettings
from os2sync_export.config import FastRAMQPISettings
from os2sync_export.config import Settings
from os2sync_export.main import create_app
from os2sync_export.os2sync import WritableOS2SyncClient

DEFAULT_AMQP_URL = "amqp://guest:guest@msg_broker:5672/os2mo"

FULL_VALIDITY = ValidityInput(from_=None, to=None)  # type: ignore[call-arg]


@pytest.fixture
async def app(monkeypatch: MonkeyPatch) -> FastAPI:
    app = create_app()
    return app


@pytest.fixture
async def graphql_client(mo_client: AsyncClient) -> AsyncIterator[GraphQLClient]:
    """Authenticated GraphQL codegen client for OS2mo."""
    graphql_client = GraphQLClient(
        url=f"{mo_client.base_url}/graphql/v25",
        http_client=mo_client,
    )
    async with graphql_client as client:
        yield client


@pytest.fixture()
def set_settings() -> Generator[Callable[..., Settings], None, None]:
    """Fixture to mock get_settings."""

    def setup_mock_settings(
        *args: Any,
        municipality=1234,
        top_unit_uuid="baccbf9b-d699-4118-a6fe-aeb813631a15",
        amqp_url: str = DEFAULT_AMQP_URL,
        client_id: str = "tester",
        client_secret: SecretStr = SecretStr("hunter2"),
        **kwargs: Any,
    ) -> Settings:
        if "top_unit_uuid" not in kwargs:
            kwargs["top_unit_uuid"] = top_unit_uuid
        settings = Settings(
            *args,
            municipality=municipality,
            fastramqpi=FastRAMQPISettings(
                amqp=AMQPConnectionSettings(url=amqp_url),  # type: ignore
                client_id=client_id,
                client_secret=client_secret,
            ),  # type: ignore
            **kwargs,
        )
        return settings

    yield setup_mock_settings


@pytest.fixture()
def mock_settings(
    set_settings: Callable[..., Settings],
) -> Generator[Settings, None, None]:
    """Fixture to mock get_settings."""
    yield set_settings()


@pytest.fixture
def graphql_session() -> Generator[AsyncMock, None, None]:
    """Fixture for the GraphQL session."""
    yield AsyncMock()


@pytest.fixture
def mock_graphql_client() -> Generator[AsyncMock, None, None]:
    """Fixture for the codegen client."""
    yield AsyncMock()


@pytest.fixture
def mock_os2sync_client(
    mock_settings,
) -> Generator[WritableOS2SyncClient, None, None]:
    """Fixture for the os2sync_client."""
    yield WritableOS2SyncClient(settings=mock_settings)


@pytest.fixture
def os2sync_client() -> Generator[AsyncMock, None, None]:
    """Fixture for the ModelClient."""
    yield AsyncMock()


async def _create_facet(graphql_client: GraphQLClient, user_key: str) -> UUID:
    r = await graphql_client.testing__create_facet(
        input=FacetCreateInput(user_key=user_key, validity=FULL_VALIDITY)
    )
    return r.uuid


async def _create_class(
    graphql_client: GraphQLClient,
    facet_uuid: UUID,
    name: str,
    user_key: str,
    scope: str | None = None,
) -> UUID:
    r = await graphql_client.testing__create_class(
        input=ClassCreateInput(
            name=name,
            user_key=user_key,
            scope=scope,
            facet_uuid=facet_uuid,
            validity=FULL_VALIDITY,
        )
    )
    return r.uuid


@pytest.fixture
async def create_org_unit_type_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "org_unit_type")


@pytest.fixture
async def create_address_type_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "employee_address_type")


@pytest.fixture
async def create_email_address_type(
    graphql_client: GraphQLClient, create_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, create_address_type_facet, "email", "email", "EMAIL"
    )


@pytest.fixture
async def create_mobile_address_type(
    graphql_client: GraphQLClient, create_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, create_address_type_facet, "Mobile", "mobile", "PHONE"
    )


@pytest.fixture
async def create_landline_address_type(
    graphql_client: GraphQLClient, create_address_type_facet: UUID
) -> UUID:
    return await _create_class(
        graphql_client, create_address_type_facet, "Landline", "landline", "PHONE"
    )


@pytest.fixture
async def create_org_unit_type(
    graphql_client: GraphQLClient,
    create_org_unit_type_facet: UUID,
) -> UUID:
    return await _create_class(
        graphql_client, create_org_unit_type_facet, "afdeling", "unit"
    )


@pytest.fixture
async def create_org_unit(
    graphql_client: GraphQLClient, mock_settings, create_org_unit_type
) -> TestingOrgUnitCreateOrgUnitCreate:
    _ = await graphql_client.testing__org_unit_create(
        input=OrganisationUnitCreateInput(
            uuid=mock_settings.top_unit_uuid,
            name="Andeby kommune",
            org_unit_type=create_org_unit_type,
            parent=None,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    return await graphql_client.testing__org_unit_create(
        input=OrganisationUnitCreateInput(
            name="Andeby Rådhus",
            org_unit_type=create_org_unit_type,
            parent=mock_settings.top_unit_uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )


@pytest.fixture
async def create_person(
    graphql_client: GraphQLClient,
) -> TestingEmployeeCreateEmployeeCreate:
    return await graphql_client.testing__employee_create(
        input=EmployeeCreateInput(
            uuid=uuid4(),
            given_name="Brian",
            surname="Graversen",
            user_key="BSG",
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )


@pytest.fixture
async def create_AD_itsystem(graphql_client: GraphQLClient) -> UUID:
    return (
        await graphql_client.testing__create_itsystem(
            input=ITSystemCreateInput(
                name="Active Directory",
                user_key="Active Directory",
                validity=FULL_VALIDITY,  # type: ignore[arg-type]
            )
        )
    ).uuid


@pytest.fixture()
async def create_FK_itsystem(graphql_client: GraphQLClient) -> UUID:
    return (
        await graphql_client.testing__create_itsystem(
            input=ITSystemCreateInput(
                name="FK-org uuid",
                user_key="FK-ORG-UUID",
                validity=FULL_VALIDITY,  # type: ignore[arg-type]
            )
        )
    ).uuid


@pytest.fixture
async def engagement_type_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "engagement_type")


@pytest.fixture
async def job_function_facet(graphql_client: GraphQLClient) -> UUID:
    return await _create_facet(graphql_client, "job_function")


@pytest.fixture
async def create_engagement_type(
    graphql_client: GraphQLClient,
    engagement_type_facet: UUID,
) -> UUID:
    return await _create_class(graphql_client, engagement_type_facet, "ansat", "-")


@pytest.fixture
async def create_job_function(
    graphql_client: GraphQLClient,
    job_function_facet: UUID,
) -> UUID:
    return await _create_class(graphql_client, job_function_facet, "Tester", "test")


@pytest.fixture
async def create_engagements(
    graphql_client: GraphQLClient,
    create_person,
    create_org_unit,
    create_engagement_type,
    create_job_function,
) -> list[EngagementCreateInput]:
    engagement_uuid1, engagement_uuid2 = uuid4(), uuid4()

    engagements = [
        EngagementCreateInput(
            uuid=engagement_uuid1,
            employee=create_person.uuid,
            org_unit=create_org_unit.uuid,
            user_key="eng1",
            engagement_type=create_engagement_type,
            job_function=create_job_function,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        ),
        EngagementCreateInput(
            uuid=engagement_uuid2,
            employee=create_person.uuid,
            org_unit=create_org_unit.uuid,
            user_key="eng2",
            engagement_type=create_engagement_type,
            job_function=create_job_function,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        ),
    ]
    for e in engagements:
        await graphql_client.testing__engagement_create(input=e)
    return engagements


@pytest.fixture
async def create_engagement(
    graphql_client: GraphQLClient,
    create_person,
    create_org_unit,
    create_engagement_type,
    create_job_function,
) -> TestingEngagementCreateEngagementCreate:
    engagement_uuid = uuid4()

    return await graphql_client.testing__engagement_create(
        input=EngagementCreateInput(
            uuid=engagement_uuid,
            employee=create_person.uuid,
            org_unit=create_org_unit.uuid,
            user_key="eng1",
            engagement_type=create_engagement_type,
            job_function=create_job_function,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
