# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
from datetime import datetime
from unittest.mock import AsyncMock
from uuid import UUID
from uuid import uuid4

import pytest
from fastapi import FastAPI
from fastramqpi.pytest_plugin import run_server
from fastramqpi.pytest_util import retrying
from tenacity import stop_before_delay

from os2sync_export.autogenerated_graphql_client import GraphQLClient
from os2sync_export.autogenerated_graphql_client import (
    TestingOrgUnitCreateOrgUnitCreate,
)
from os2sync_export.autogenerated_graphql_client.client import gql
from os2sync_export.autogenerated_graphql_client.input_types import ClassCreateInput
from os2sync_export.autogenerated_graphql_client.input_types import FacetCreateInput
from os2sync_export.autogenerated_graphql_client.input_types import KLECreateInput
from os2sync_export.autogenerated_graphql_client.input_types import (
    OrganisationUnitTerminateInput,
)
from os2sync_export.autogenerated_graphql_client.input_types import RAValidityInput
from os2sync_export.main import sync_orgunit
from os2sync_export.os2sync_models import OrgUnit


async def get_pending_org_unit_events(
    graphql_client: GraphQLClient, subject: str
) -> list[dict]:
    response = await graphql_client.execute(
        query=gql("""
            query PendingOrgUnitEvents($subject: [String!]) {
              events(filter: {subjects: $subject}) {
                objects {
                  subject
                }
              }
            }
        """),
        variables={"subject": [subject]},
    )
    data = graphql_client.get_data(response)
    return data["events"]["objects"]


@pytest.mark.integration_test
async def test_unit_not_found(
    graphql_client: GraphQLClient,
    set_settings,
) -> None:
    # Arrange
    os2sync_mock = AsyncMock()
    uuid = uuid4()

    # Act
    result = await sync_orgunit(
        settings=set_settings(),
        graphql_client=graphql_client,
        os2sync_client=os2sync_mock,
        uuid=uuid,
    )

    # Assert
    # A unit MO has never known about is treated the same as a deleted one:
    # it must be removed from fk-org rather than left dangling there.
    assert result is None
    os2sync_mock.delete_orgunit.assert_awaited_once_with(uuid)
    os2sync_mock.update_org_unit.assert_not_called()


@pytest.mark.integration_test
async def test_unit_not_relevant(
    graphql_client: GraphQLClient,
    set_settings,
    create_org_unit,
) -> None:
    # Arrange
    os2sync_mock = AsyncMock()

    # Act
    await sync_orgunit(
        settings=set_settings(top_unit_uuid=uuid4()),
        graphql_client=graphql_client,
        os2sync_client=os2sync_mock,
        uuid=create_org_unit.uuid,
    )
    # Assert
    os2sync_mock.update_org_unit.assert_not_called()
    os2sync_mock.delete_orgunit.assert_called_once_with(create_org_unit.uuid)


@pytest.mark.integration_test
async def test_unit_synced(
    graphql_client: GraphQLClient,
    set_settings,
    create_org_unit,
) -> None:
    # Arrange
    os2sync_mock = AsyncMock()
    expected = OrgUnit(
        Uuid=create_org_unit.uuid,
        ShortKey=None,
        Name="Andeby Rådhus",
        ParentOrgUnitUuid=UUID("baccbf9b-d699-4118-a6fe-aeb813631a15"),
        PayoutUnitUuid=None,
        ManagerUuid=None,
        PhoneNumber=None,
        Email=None,
        Location=None,
        LOSShortName=None,
        LOSId=None,
        DtrId=None,
        ContactOpenHours=None,
        EmailRemarks=None,
        Contact=None,
        PostReturn=None,
        PhoneOpenHours=None,
        Ean=None,
        Url=None,
        Landline=None,
        Post=None,
        PostSecondary=None,
        FOA=None,
        PNR=None,
        SOR=None,
        Tasks=set(),
        ItSystems=set(),
        ContactForTasks=set(),
        ContactPlaces=set(),
    )
    # Act
    await sync_orgunit(
        settings=set_settings(),
        graphql_client=graphql_client,
        os2sync_client=os2sync_mock,
        uuid=create_org_unit.uuid,
    )
    # Assert

    os2sync_mock.update_org_unit.assert_called_once_with(
        create_org_unit.uuid, org_unit=expected
    )
    os2sync_mock.delete_orgunit.assert_not_called()


@pytest.mark.integration_test
async def test_unit_with_terminated_KLE(
    graphql_client: GraphQLClient,
    set_settings,
    create_org_unit,
) -> None:
    """Test that if a unit is marked with a KLE number that is terminated the KLE number is not send to os2sync."""
    # Arrange
    os2sync_mock = AsyncMock()
    # Create KLE facets and classes
    kle_aspect_facet = await graphql_client.testing__create_facet(
        input=FacetCreateInput(
            user_key="kle_aspect",
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    kle_number_facet = await graphql_client.testing__create_facet(
        input=FacetCreateInput(
            user_key="kle_number",
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    kle_aspect = await graphql_client.testing__create_class(
        input=ClassCreateInput(
            name="udførende",
            user_key="udførende",
            facet_uuid=kle_aspect_facet.uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    kle_number = await graphql_client.testing__create_class(
        input=ClassCreateInput(
            name="test",
            user_key="1.2.3",
            facet_uuid=kle_number_facet.uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    # Create a KLE number that is no longer active
    past_kle_number = await graphql_client.testing__create_class(
        input=ClassCreateInput(
            name="previous test",
            user_key="0.0.1",
            facet_uuid=kle_number_facet.uuid,
            validity=RAValidityInput(
                from_=datetime(1970, 1, 1),
                to=datetime(2020, 1, 1),  # type: ignore
            ),
        )
    )
    # Connect both the active and the inactive KLE number to the orgunit.
    await graphql_client.testing__kle_create(
        input=KLECreateInput(
            org_unit=create_org_unit.uuid,
            kle_number=kle_number.uuid,
            kle_aspects=[kle_aspect.uuid],
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    await graphql_client.testing__kle_create(
        input=KLECreateInput(
            org_unit=create_org_unit.uuid,
            kle_number=past_kle_number.uuid,
            kle_aspects=[kle_aspect.uuid],
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    # Expect only the active KLE number to be present
    expected = OrgUnit(
        Uuid=create_org_unit.uuid,
        ShortKey=None,
        Name="Andeby Rådhus",
        ParentOrgUnitUuid=UUID("baccbf9b-d699-4118-a6fe-aeb813631a15"),
        PayoutUnitUuid=None,
        ManagerUuid=None,
        PhoneNumber=None,
        Email=None,
        Location=None,
        LOSShortName=None,
        LOSId=None,
        DtrId=None,
        ContactOpenHours=None,
        EmailRemarks=None,
        Contact=None,
        PostReturn=None,
        PhoneOpenHours=None,
        Ean=None,
        Url=None,
        Landline=None,
        Post=None,
        PostSecondary=None,
        FOA=None,
        PNR=None,
        SOR=None,
        Tasks={kle_number.uuid},
        ItSystems=set(),
        ContactForTasks=set(),
        ContactPlaces=set(),
    )
    # Act
    await sync_orgunit(
        settings=set_settings(),
        graphql_client=graphql_client,
        os2sync_client=os2sync_mock,
        uuid=create_org_unit.uuid,
    )
    # Assert

    os2sync_mock.update_org_unit.assert_called_once_with(
        create_org_unit.uuid, org_unit=expected
    )
    os2sync_mock.delete_orgunit.assert_not_called()


@pytest.mark.integration_test
async def test_event_inactive_org_unit(
    app: FastAPI,
    graphql_client: GraphQLClient,
    create_org_unit: TestingOrgUnitCreateOrgUnitCreate,
) -> None:
    # Act
    # Terminate the org unit so it is no longer active in MO.
    await graphql_client.testing__org_unit_terminate(
        input=OrganisationUnitTerminateInput(
            uuid=create_org_unit.uuid,
            to=datetime(2025, 1, 1, 0, 0, 0),
        )
    )
    async with run_server(app):
        # Enqueue an internal org_unit sync event for the terminated unit.
        await graphql_client.event_send(
            namespace="os2sync_export",
            routing_key="org_unit",
            subject=str(create_org_unit.uuid),
        )

        # The event must be processed even though the org unit is no longer active.
        # Before the fix the NotFoundError raised by sync_orgunit crashed the
        # /sync/org_unit handler, so the event was never acknowledged and stayed
        # stuck in the queue forever.
        async for attempt in retrying(stop=stop_before_delay(60)):
            with attempt:
                assert (
                    await get_pending_org_unit_events(
                        graphql_client, str(create_org_unit.uuid)
                    )
                    == []
                )
