# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
from datetime import UTC
from datetime import datetime
from unittest.mock import patch
from uuid import uuid4

import pytest
from httpx import AsyncClient

from os2sync_export.autogenerated_graphql_client import GraphQLClient
from os2sync_export.autogenerated_graphql_client.input_types import ITUserCreateInput
from os2sync_export.autogenerated_graphql_client.input_types import RAValidityInput
from os2sync_export.os2sync import OS2SyncClient


@pytest.mark.parametrize("dry_run", [True, False])
@pytest.mark.integration_test
async def test_cleanup_stale_users(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    mock_settings,
    create_person,
    create_engagements,
    create_AD_itsystem,
    create_FK_itsystem,
    set_settings,
    dry_run,
) -> None:
    # Arrange
    fk_uuid1 = uuid4()
    fk_uuid2 = uuid4()
    # Create two itusers to ensure we find both
    await graphql_client.testing__ituser_create(
        input=ITUserCreateInput(
            person=create_person.uuid,
            user_key="AD-username",
            external_id=str(fk_uuid1),
            engagements=[e.uuid for e in create_engagements],
            itsystem=create_AD_itsystem,
            validity=RAValidityInput(
                from_=datetime(2020, 1, 1, 0, 0, 0, tzinfo=UTC),  # type: ignore
                to=None,
            ),
        )
    )
    await graphql_client.testing__ituser_create(
        input=ITUserCreateInput(
            person=create_person.uuid,
            user_key="AD-username",
            external_id=str(fk_uuid2),
            engagements=[e.uuid for e in create_engagements],
            itsystem=create_AD_itsystem,
            validity=RAValidityInput(
                from_=datetime(2020, 1, 1, 0, 0, 0, tzinfo=UTC),  # type: ignore
                to=None,
            ),
        )
    )
    # trigger the sync to ensure the fk-ids are created
    await test_client.post(f"/trigger/user/{create_person.uuid}")
    # Act

    with patch.object(OS2SyncClient, "cleanup_users") as mock_cleanup:
        await test_client.post("cleanup_users", params={"dry_run": dry_run})

    # Assert
    mock_cleanup.assert_called_once_with({fk_uuid1, fk_uuid2}, dry_run=dry_run)


@pytest.mark.integration_test
async def test_cleanup_anti_footgun(
    test_client: AsyncClient,
    mock_settings,
    set_settings,
) -> None:
    """Ensure that we never call the cleanup API with an empty list as this would delete all users from fk-org"""

    # Act
    with patch.object(OS2SyncClient, "cleanup_users") as mock_cleanup:
        await test_client.post("cleanup_users")

    # Assert
    mock_cleanup.assert_not_called()
