# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
from datetime import datetime
from datetime import timedelta
from unittest.mock import MagicMock
from unittest.mock import call
from uuid import UUID
from uuid import uuid4

import pytest
from fastramqpi.pytest_util import retrying
from httpx import AsyncClient
from more_itertools import first
from more_itertools import one
from tenacity import stop_before_delay

from os2sync_export.autogenerated_graphql_client import GraphQLClient
from os2sync_export.autogenerated_graphql_client.input_types import AddressCreateInput
from os2sync_export.autogenerated_graphql_client.input_types import ClassFilter
from os2sync_export.autogenerated_graphql_client.input_types import (
    EngagementCreateInput,
)
from os2sync_export.autogenerated_graphql_client.input_types import (
    EngagementUpdateInput,
)
from os2sync_export.autogenerated_graphql_client.input_types import FacetFilter
from os2sync_export.autogenerated_graphql_client.input_types import ITSystemFilter
from os2sync_export.autogenerated_graphql_client.input_types import ITUserCreateInput
from os2sync_export.autogenerated_graphql_client.input_types import RAValidityInput
from os2sync_export.autogenerated_graphql_client.read_user_i_t_accounts import (
    ReadUserITAccountsEmployeesObjectsCurrentFkOrgUuids,
)
from os2sync_export.os2mo_gql import read_fk_users_from_person
from os2sync_export.os2mo_gql import sync_mo_user_to_fk_org
from os2sync_export.os2sync_models import Person
from os2sync_export.os2sync_models import Position
from os2sync_export.os2sync_models import User


@pytest.mark.integration_test
async def test_event(
    test_client: AsyncClient,
    graphql_client: GraphQLClient,
    create_person,
    create_engagements,
) -> None:
    # Arrange
    adguid = uuid4()
    person_uuid = create_person.uuid

    itsystem_AD = await graphql_client.testing__get_itsystem(
        ITSystemFilter(user_keys=["Active Directory"], from_date=None, to_date=None)
    )
    AD_uuid = first(itsystem_AD.objects).uuid
    # Act
    # This creates an event that the integration reacts to
    await graphql_client.testing__ituser_create(
        input=ITUserCreateInput(
            person=person_uuid,
            user_key="AD-username 1",
            external_id=str(adguid),
            engagements=[e.uuid for e in create_engagements],
            itsystem=AD_uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    # Check that only the AD account exists in MO
    fk_accounts, ad_accounts = await read_fk_users_from_person(
        graphql_client=graphql_client,
        uuid=person_uuid,
        it_user_keys=["Active Directory"],
    )
    assert len(ad_accounts) == 1
    assert fk_accounts == []

    # Assert
    async for attempt in retrying(stop=stop_before_delay(60)):
        with attempt:
            # Check that the fk-org account has been created
            fk_accounts, ad_accounts = await read_fk_users_from_person(
                graphql_client=graphql_client,
                uuid=person_uuid,
                it_user_keys=["Active Directory"],
            )
            fk_account = one(fk_accounts)
            assert UUID(fk_account.user_key) == adguid
            assert UUID(fk_account.external_id) == adguid


@pytest.mark.integration_test
async def test_account_with_addresses(
    graphql_client: GraphQLClient,
    create_person,
    create_engagements,
    set_settings,
) -> None:
    # Test that emails are sent to fk-org with their correct account.
    # Arrange
    adguid1 = uuid4()
    adguid2 = uuid4()
    os2sync_mock = MagicMock()
    person_uuid = create_person.uuid

    itsystem_AD = await graphql_client.testing__get_itsystem(
        ITSystemFilter(user_keys=["Active Directory"], from_date=None, to_date=None)
    )
    AD_uuid = first(itsystem_AD.objects).uuid
    # AD users
    ad_user_1 = await graphql_client.testing__ituser_create(
        input=ITUserCreateInput(
            person=person_uuid,
            user_key="AD-username 1",
            external_id=str(adguid1),
            engagements=[e.uuid for e in create_engagements],
            itsystem=AD_uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    ad_user_2 = await graphql_client.testing__ituser_create(
        input=ITUserCreateInput(
            person=person_uuid,
            user_key="AD-username 2",
            external_id=str(adguid2),
            engagements=[e.uuid for e in create_engagements],
            itsystem=AD_uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    # find address types:
    email_address_types = await graphql_client.testing__get_class(
        ClassFilter(
            facet=FacetFilter(user_keys=["employee_address_type"]),  # type: ignore
            scope=["EMAIL"],
        )
    )
    email_address_type_uuid = first(email_address_types.objects).uuid
    mobile_address_types = await graphql_client.testing__get_class(
        ClassFilter(
            facet=FacetFilter(user_keys=["employee_address_type"]),  # type: ignore
            scope=["PHONE"],
            user_keys=["mobile"],
        )
    )
    mobile_address_type_uuid = first(mobile_address_types.objects).uuid
    landline_address_types = await graphql_client.testing__get_class(
        ClassFilter(
            facet=FacetFilter(user_keys=["employee_address_type"]),  # type: ignore
            scope=["PHONE"],
            user_keys=["landline"],
        )
    )
    landline_address_type_uuid = first(landline_address_types.objects).uuid

    settings = set_settings(
        email_scope_classes=[email_address_type_uuid],
        phone_scope_classes=[mobile_address_type_uuid],
        landline_scope_classes=[landline_address_type_uuid],
    )
    # Create two email-addresses - one connected to each it-account
    await graphql_client.testing__address_create(
        input=AddressCreateInput(
            employee=create_person.uuid,
            value="bsg@example.com",
            address_type=email_address_type_uuid,
            ituser=ad_user_1.uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    await graphql_client.testing__address_create(
        input=AddressCreateInput(
            employee=create_person.uuid,
            value="bsg2@example.com",
            address_type=email_address_type_uuid,
            ituser=ad_user_2.uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    # Create a phone number for one it-account
    await graphql_client.testing__address_create(
        input=AddressCreateInput(
            employee=create_person.uuid,
            value="11223344",
            address_type=mobile_address_type_uuid,
            ituser=ad_user_1.uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    # Create a landlines for the other it_account
    await graphql_client.testing__address_create(
        input=AddressCreateInput(
            employee=create_person.uuid,
            value="12345678",
            address_type=landline_address_type_uuid,
            ituser=ad_user_2.uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    # Act
    await sync_mo_user_to_fk_org(
        uuid=person_uuid,
        graphql_client=graphql_client,
        settings=settings,
        os2sync_client=os2sync_mock,
    )
    # Assert
    assert os2sync_mock.update_user.call_count == 2
    os2sync_mock.delete_user.assert_not_called()

    expected = [
        call(
            User(
                Uuid=adguid1,
                ShortKey=None,
                UserId="AD-username 1",
                Person=Person(Name="Brian Graversen", Cpr=None),
                Positions=[
                    Position(
                        Name="Tester",
                        OrgUnitUuid=first(create_engagements).org_unit,
                        StartDate=datetime(1970, 1, 1),
                        StopDate=None,
                    ),
                    Position(
                        Name="Tester",
                        OrgUnitUuid=first(create_engagements).org_unit,
                        StartDate=datetime(1970, 1, 1),
                        StopDate=None,
                    ),
                ],
                PhoneNumber="11223344",
                Landline=None,
                Email="bsg@example.com",
                Location=None,
                RacfID=None,
                FMKID=None,
                DateTime=None,
            )
        ),
        call(
            User(
                Uuid=adguid2,
                ShortKey=None,
                UserId="AD-username 2",
                Person=Person(Name="Brian Graversen", Cpr=None),
                Positions=[
                    Position(
                        Name="Tester",
                        OrgUnitUuid=first(create_engagements).org_unit,
                        StartDate=datetime(1970, 1, 1),
                        StopDate=None,
                    ),
                    Position(
                        Name="Tester",
                        OrgUnitUuid=first(create_engagements).org_unit,
                        StartDate=datetime(1970, 1, 1),
                        StopDate=None,
                    ),
                ],
                PhoneNumber=None,
                Landline="12345678",
                Email="bsg2@example.com",
                Location=None,
                RacfID=None,
                FMKID=None,
                DateTime=None,
            ),
        ),
    ]
    assert len(os2sync_mock.update_user.call_args_list) == 2
    for c in os2sync_mock.update_user.call_args_list:
        assert c in expected


@pytest.mark.integration_test
async def test_account_with_no_relevant_engagement(
    graphql_client: GraphQLClient,
    create_person,
    create_engagements,
    set_settings,
) -> None:
    # Arrange
    # Set top_unit_uuid to a new uuid to ensure the engagement is not considered relevant.
    settings = set_settings(top_unit_uuid=uuid4())
    adguid = uuid4()
    fk_org_uuid = uuid4()
    os2sync_mock = MagicMock()
    person_uuid = create_person.uuid
    itsystem_AD = await graphql_client.testing__get_itsystem(
        ITSystemFilter(user_keys=["Active Directory"], from_date=None, to_date=None)
    )
    AD_uuid = first(itsystem_AD.objects).uuid
    # AD users
    await graphql_client.testing__ituser_create(
        input=ITUserCreateInput(
            person=person_uuid,
            user_key="AD-username 1",
            external_id=str(adguid),
            engagements=[e.uuid for e in create_engagements],
            itsystem=AD_uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    # Create an fk-org user and check that it will not be terminated
    itsystem_FK = await graphql_client.testing__get_itsystem(
        ITSystemFilter(user_keys=["FK-ORG-UUID"], from_date=None, to_date=None)
    )
    FK_uuid = first(itsystem_FK.objects).uuid
    fk_account = await graphql_client.testing__ituser_create(
        input=ITUserCreateInput(
            uuid=uuid4(),
            person=person_uuid,
            user_key=str(adguid),
            external_id=str(fk_org_uuid),
            itsystem=FK_uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    # Act
    await sync_mo_user_to_fk_org(
        uuid=person_uuid,
        graphql_client=graphql_client,
        settings=settings,
        os2sync_client=os2sync_mock,
    )
    # Assert
    os2sync_mock.update_user.assert_not_called()
    os2sync_mock.delete_user.assert_called_once_with(fk_org_uuid)

    # Check that the expected it-accounts exists in MO
    fk_accounts, it_accounts = await read_fk_users_from_person(
        graphql_client=graphql_client,
        uuid=person_uuid,
        it_user_keys=["Active Directory"],
    )
    assert len(it_accounts) == 1
    # Even though the engagement is no longer relevant we keep the fk-org account
    assert fk_accounts == [
        ReadUserITAccountsEmployeesObjectsCurrentFkOrgUuids(
            uuid=fk_account.uuid, user_key=str(adguid), external_id=str(fk_org_uuid)
        )
    ]


@pytest.mark.integration_test
async def test_startdate(
    graphql_client: GraphQLClient,
    mock_settings,
    create_person,
    create_engagements,
    set_settings,
) -> None:
    # Arrange
    adguid = uuid4()
    fk_org_uuid = uuid4()
    os2sync_mock = MagicMock()
    person_uuid = create_person.uuid
    itsystem_AD = await graphql_client.testing__get_itsystem(
        ITSystemFilter(user_keys=["Active Directory"], from_date=None, to_date=None)
    )
    AD_uuid = first(itsystem_AD.objects).uuid
    # Edit the engagements to start earlier
    for e in create_engagements:
        await graphql_client.testing__engagement_update(
            input=EngagementUpdateInput(
                uuid=e.uuid,
                validity=RAValidityInput(from_=datetime(1960, 1, 1)),  # type: ignore
            )
        )
    # AD users
    await graphql_client.testing__ituser_create(
        input=ITUserCreateInput(
            person=person_uuid,
            user_key="AD-username",
            external_id=str(adguid),
            engagements=[e.uuid for e in create_engagements],
            itsystem=AD_uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    # Create an fk-org user and check that it will not be terminated
    itsystem_FK = await graphql_client.testing__get_itsystem(
        ITSystemFilter(user_keys=["FK-ORG-UUID"], from_date=None, to_date=None)
    )
    FK_uuid = first(itsystem_FK.objects).uuid
    fk_account = await graphql_client.testing__ituser_create(
        input=ITUserCreateInput(
            uuid=uuid4(),
            person=person_uuid,
            user_key=str(adguid),
            external_id=str(fk_org_uuid),
            itsystem=FK_uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )
    expected = User(
        Uuid=fk_org_uuid,
        ShortKey=None,
        UserId="AD-username",
        Person=Person(Name="Brian Graversen", Cpr=None),
        Positions=[
            Position(
                Name="Tester",
                OrgUnitUuid=first(create_engagements).org_unit,
                StartDate=datetime(1960, 1, 1),
                StopDate=None,
            ),
            Position(
                Name="Tester",
                OrgUnitUuid=first(create_engagements).org_unit,
                StartDate=datetime(1960, 1, 1),
                StopDate=None,
            ),
        ],
        PhoneNumber=None,
        Landline=None,
        Email=None,
        Location=None,
        RacfID=None,
        FMKID=None,
        DateTime=None,
    )

    # Act
    await sync_mo_user_to_fk_org(
        uuid=person_uuid,
        graphql_client=graphql_client,
        settings=mock_settings,
        os2sync_client=os2sync_mock,
    )
    # Assert
    os2sync_mock.update_user.assert_called_once_with(expected)
    os2sync_mock.delete_user.assert_not_called()

    # Check that the expected it-accounts exists in MO
    fk_accounts, it_accounts = await read_fk_users_from_person(
        graphql_client=graphql_client,
        uuid=person_uuid,
        it_user_keys=["Active Directory"],
    )
    assert len(it_accounts) == 1
    # Even though the engagement is no longer relevant we keep the fk-org account
    assert fk_accounts == [
        ReadUserITAccountsEmployeesObjectsCurrentFkOrgUuids(
            uuid=fk_account.uuid, user_key=str(adguid), external_id=str(fk_org_uuid)
        )
    ]


@pytest.mark.integration_test
async def test_future_engagement(
    graphql_client: GraphQLClient,
    mock_settings,
    create_person,
    create_org_unit,
    set_settings,
) -> None:
    # Arrange
    # Create an engagement that starts in the future, link it to a current AD account and assert that it would be written to os2sync
    engagement_startdate = datetime.now() + timedelta(days=30)
    adguid = uuid4()
    os2sync_mock = MagicMock()
    # Mock that user is not in os2sync already
    os2sync_mock.os2sync_get_user.side_effect = [KeyError]
    person_uuid = create_person.uuid
    itsystem_AD = await graphql_client.testing__get_itsystem(
        ITSystemFilter(user_keys=["Active Directory"], from_date=None, to_date=None)
    )
    AD_uuid = first(itsystem_AD.objects).uuid

    all_engagement_types = await graphql_client.testing__get_class(
        ClassFilter(
            facet=FacetFilter(
                user_keys=["engagement_type"], from_date=None, to_date=None
            ),
            from_date=None,
            to_date=None,
        )
    )

    engagement_type = first(all_engagement_types.objects).uuid
    all_job_functions = await graphql_client.testing__get_class(
        ClassFilter(
            user_keys=["tester"],
            facet=FacetFilter(
                user_keys=["engagement_job_function"], from_date=None, to_date=None
            ),
            from_date=None,
            to_date=None,
        )
    )

    job_function = first(all_job_functions.objects).uuid
    res = await graphql_client.testing__engagement_create(
        input=EngagementCreateInput(
            employee=create_person.uuid,
            org_unit=create_org_unit.uuid,
            user_key="1234",
            engagement_type=engagement_type,
            job_function=job_function,
            validity=RAValidityInput(from_=engagement_startdate, to=None),  # type: ignore
        )
    )
    engagement_uuid = res.uuid
    # AD users
    await graphql_client.testing__ituser_create(
        input=ITUserCreateInput(
            person=person_uuid,
            user_key="AD-username",
            external_id=str(adguid),
            engagements=[engagement_uuid],
            itsystem=AD_uuid,
            validity=RAValidityInput(from_=datetime(1970, 1, 1), to=None),  # type: ignore
        )
    )

    expected = User(
        Uuid=adguid,
        ShortKey=None,
        UserId="AD-username",
        Person=Person(Name="Brian Graversen", Cpr=None),
        Positions=[
            Position(
                Name="Tester",
                OrgUnitUuid=create_org_unit.uuid,
                StartDate=engagement_startdate,
                StopDate=None,
            ),
        ],
        PhoneNumber=None,
        Landline=None,
        Email=None,
        Location=None,
        RacfID=None,
        FMKID=None,
        DateTime=None,
    )

    # Act
    await sync_mo_user_to_fk_org(
        uuid=person_uuid,
        graphql_client=graphql_client,
        settings=mock_settings,
        os2sync_client=os2sync_mock,
    )
    # Assert
    os2sync_mock.update_user.assert_called_once_with(expected)
    os2sync_mock.delete_user.assert_not_called()

    # Check that the expected it-accounts exists in MO
    fk_accounts, it_accounts = await read_fk_users_from_person(
        graphql_client=graphql_client,
        uuid=person_uuid,
        it_user_keys=["Active Directory"],
    )
    assert len(it_accounts) == 1
    # Even though the engagement is no longer relevant we keep the fk-org account
    assert one(fk_accounts).user_key == str(adguid)
    assert one(fk_accounts).external_id == str(adguid)
