# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from datetime import datetime
from unittest.mock import AsyncMock
from uuid import uuid4

import pytest
from freezegun import freeze_time
from more_itertools import first

from os2sync_export.autogenerated_graphql_client import GraphQLClient
from os2sync_export.autogenerated_graphql_client.input_types import ITSystemFilter
from os2sync_export.autogenerated_graphql_client.input_types import ITUserCreateInput
from os2sync_export.autogenerated_graphql_client.input_types import RAValidityInput
from os2sync_export.autogenerated_graphql_client.testing__employee_create import (
    TestingEmployeeCreateEmployeeCreate,
)
from os2sync_export.autogenerated_graphql_client.testing__engagement_create import (
    TestingEngagementCreateEngagementCreate,
)
from os2sync_export.os2mo_gql import sync_mo_user_to_fk_org


# We freeze time to 23:30 UTC on Jan 1st.
# In Denmark (UTC+1), this is 00:30 on Jan 2nd.
@pytest.mark.integration_test
@freeze_time("2025-01-01 23:30:00")
async def test_midnight_timezone_bug(
    graphql_client: GraphQLClient,
    create_person: TestingEmployeeCreateEmployeeCreate,
    create_engagement: TestingEngagementCreateEngagementCreate,
    mock_settings,
) -> None:
    # 1. ARRANGE
    person_uuid = create_person.uuid
    os2sync_mock = AsyncMock()

    # Get AD System UUID
    itsystem_AD = await graphql_client.testing__get_itsystem(
        ITSystemFilter(user_keys=["Active Directory"], from_date=None, to_date=None)
    )
    AD_uuid = first(itsystem_AD.objects).uuid

    # Create an IT User that is valid starting from Jan 2nd 00:00:00
    # We use a naive date here to ensure it's treated as "Local Midnight" by MO
    validity_start = datetime(2025, 1, 2, 0, 0, 0)

    await graphql_client.testing__ituser_create(
        input=ITUserCreateInput(
            person=person_uuid,
            user_key="midnight-user",
            external_id=str(uuid4()),
            engagements=[create_engagement.uuid],
            itsystem=AD_uuid,
            validity=RAValidityInput(from_=validity_start, to=None),  # type: ignore
        )
    )

    # 2. ACT
    # Run the sync. The client will calculate 'now' (frozen at 23:30 UTC) and send it to MO.
    await sync_mo_user_to_fk_org(
        uuid=person_uuid,
        graphql_client=graphql_client,
        settings=mock_settings,
        os2sync_client=os2sync_mock,
    )

    # 3. ASSERT
    assert os2sync_mock.update_user.called
