# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
from unittest.mock import AsyncMock
from uuid import UUID
from uuid import uuid4

import pytest

from os2sync_export.autogenerated_graphql_client import GraphQLClient
from os2sync_export.exceptions import NotFoundError
from os2sync_export.main import sync_orgunit
from os2sync_export.os2sync_models import OrgUnit


@pytest.mark.integration_test
async def test_unit_not_found(
    graphql_client: GraphQLClient,
    set_settings,
) -> None:
    # Arrange
    os2sync_mock = AsyncMock()

    # Act
    # Assert
    with pytest.raises(NotFoundError):
        await sync_orgunit(
            settings=set_settings(),
            graphql_client=graphql_client,
            os2sync_client=os2sync_mock,
            uuid=uuid4(),
        )
    os2sync_mock.delete_orgunit.assert_not_called()
    os2sync_mock.update_org_unit.assert_not_called()


@pytest.mark.integration_test
async def test_unit_not_relevant(
    graphql_client: GraphQLClient,
    set_settings,
    create_org_unit,
) -> None:
    # Arrange
    os2sync_mock = AsyncMock()

    # Act
    await sync_orgunit(
        settings=set_settings(top_unit_uuid=uuid4()),
        graphql_client=graphql_client,
        os2sync_client=os2sync_mock,
        uuid=create_org_unit.uuid,
    )
    # Assert
    os2sync_mock.update_org_unit.assert_not_called()
    os2sync_mock.delete_orgunit.assert_called_once_with(create_org_unit.uuid)


@pytest.mark.integration_test
async def test_unit_synced(
    graphql_client: GraphQLClient,
    set_settings,
    create_org_unit,
) -> None:
    # Arrange
    os2sync_mock = AsyncMock()
    expected = OrgUnit(
        Uuid=create_org_unit.uuid,
        ShortKey=None,
        Name="Andeby Rådhus",
        ParentOrgUnitUuid=UUID("baccbf9b-d699-4118-a6fe-aeb813631a15"),
        PayoutUnitUuid=None,
        ManagerUuid=None,
        PhoneNumber=None,
        Email=None,
        Location=None,
        LOSShortName=None,
        LOSId=None,
        DtrId=None,
        ContactOpenHours=None,
        EmailRemarks=None,
        Contact=None,
        PostReturn=None,
        PhoneOpenHours=None,
        Ean=None,
        Url=None,
        Landline=None,
        Post=None,
        PostSecondary=None,
        FOA=None,
        PNR=None,
        SOR=None,
        Tasks=set(),
        ItSystems=set(),
        ContactForTasks=set(),
        ContactPlaces=set(),
    )
    # Act
    await sync_orgunit(
        settings=set_settings(),
        graphql_client=graphql_client,
        os2sync_client=os2sync_mock,
        uuid=create_org_unit.uuid,
    )
    # Assert

    os2sync_mock.update_org_unit.assert_called_once_with(
        create_org_unit.uuid, org_unit=expected
    )
    os2sync_mock.delete_orgunit.assert_not_called()
