# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
from uuid import UUID

import structlog
from more_itertools import one
from more_itertools import only

from os2sync_export.autogenerated_graphql_client.read_user_i_t_accounts import (
    ReadUserITAccountsEmployeesObjectsCurrentADUsers,
)
from os2sync_export.autogenerated_graphql_client.read_user_i_t_accounts import (
    ReadUserITAccountsEmployeesObjectsCurrentFkOrgUsers,
)
from os2sync_export.config import Settings
from os2sync_export.depends import GraphQLClient
from os2sync_export.os2sync import OS2SyncClient

logger = structlog.stdlib.get_logger()


async def read_fk_users_from_person(
    graphql_client: GraphQLClient, uuid: UUID, it_user_keys: list[str]
) -> tuple[
    list[ReadUserITAccountsEmployeesObjectsCurrentFkOrgUsers],
    list[ReadUserITAccountsEmployeesObjectsCurrentADUsers],
]:
    it_accounts = await graphql_client.read_user_i_t_accounts(
        uuid=uuid, it_user_keys=it_user_keys
    )
    current_accounts = one(it_accounts.objects).current
    if current_accounts is None:
        return [], []
    fk_accounts = current_accounts.fk_org_users
    ad_accounts = current_accounts.a_d_users
    return fk_accounts, ad_accounts


async def ensure_mo_fk_org_user_exists(
    graphql_client: GraphQLClient,
    os2sync_user: User,
    fk_org_it_users: list[ReadUserITAccountsEmployeesObjectsCurrentFkOrgUuids],
):
    fk_org_account = only(
        filter(lambda f: f.external_id == os2sync_user.Uuid, fk_org_it_users)
    )
    if fk_org_account is None:
        # New user, create it-user in MO. This should trigger a new sync of that user.
        pass
    pass


async def delete_fk_org_user(
    fk_org_it_user: ReadUserITAccountsEmployeesObjectsCurrentFkOrgUsers,
):
    raise NotImplementedError


def convert_and_filter(
    settings: Settings,
    fk_org_users: list[ReadUserITAccountsEmployeesObjectsCurrentFkOrgUuids],
    it_users: list[ReadUserITAccountsEmployeesObjectsCurrentItusers],
) -> tuple[list[User], set[UUID]]:
    # TODO: add filtering for it_users
    delete_fk_org_users = {
        UUID(fk_org_user.external_id)
        for fk_org_user in fk_org_users
        if fk_org_user.external_id not in {a.external_id for a in it_users}
    }

    return [convert_to_os2sync(it_user) for it_user in it_users], delete_fk_org_users


async def delete_mo_fk_org_users(
    graphql_client: GraphQLClient, external_id: UUID
) -> None:
    pass


def convert_to_os2sync(it):
    return it


async def sync_mo_user_to_fk_org(
    graphql_client: GraphQLClient,
    settings: Settings,
    os2sync_client: OS2SyncClient,
    uuid: UUID,
):
    fk_org_users, it_users = await read_fk_users_from_person(
        graphql_client=graphql_client,
        uuid=uuid,
        it_user_keys=settings.uuid_from_it_systems,
    )
    logger.info(
        "Found the following itusers",
        uuid=uuid,
        fk_org_users=fk_org_users,
        ad_users=it_users,
    )
    updates_fk, deletes_fk = convert_and_filter(settings, fk_org_users, it_users)
    for os2sync_user in updates_fk:
        await ensure_mo_fk_org_user_exists(graphql_client, os2sync_user, fk_org_users)
        os2sync_client.update_user(os2sync_user)
    for deleted_user_uuid in deletes_fk:
        await delete_mo_fk_org_users(graphql_client, deleted_user_uuid)
        os2sync_client.delete_user(deleted_user_uuid)
