# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
from datetime import date
from datetime import datetime
from typing import Optional
from typing import Set
from uuid import UUID

from fastapi.encoders import jsonable_encoder
from more_itertools import first
from more_itertools import one
from pydantic import BaseModel
from pydantic import Extra

from os2sync_export.autogenerated_graphql_client.read_user import (
    ReadUserItusersObjectsCurrent,
)
from os2sync_export.config import Settings


class OrgUnit(BaseModel):
    """API model for os2sync

    https://www.os2sync.dk/downloads/API%20Documentation.pdf

    public string ShortKey;
    public string Name;
    public string ParentOrgUnitUuid;
    public string PayoutUnitUuid;
    public string ManagerUuid;
    public DateTime Timestamp;
    public string PhoneNumber;
    public string Email;
    public string Location;
    public string LOSShortName;
    public string LOSId;
    public string DtrId;
    public string ContactOpenHours;
    public string EmailRemarks;
    public string Contact;
    public string PostReturn;
    public string PhoneOpenHours;
    public string Ean;
    public string Url;
    public string Landline;
    public string Post;
    public string FOA;
    public string PNR;
    public string SOR;
    public OrgUnitType Type;
    public List<string> Tasks;
    public List<string> ItSystems;
    public List<string> ContactForTasks;
    """

    class Config:
        extra = Extra.forbid

    def json(self):
        return jsonable_encoder(self.dict())

    Uuid: UUID
    ShortKey: Optional[str] = None
    Name: Optional[str]
    ParentOrgUnitUuid: Optional[UUID]
    PayoutUnitUuid: Optional[UUID] = None
    ManagerUuid: Optional[UUID] = None
    PhoneNumber: Optional[str] = None
    Email: Optional[str] = None
    Location: Optional[str] = None
    LOSShortName: Optional[str] = None
    LOSId: Optional[str] = None
    DtrId: Optional[str] = None
    ContactOpenHours: Optional[str] = None
    EmailRemarks: Optional[str] = None
    Contact: Optional[str] = None
    PostReturn: Optional[str] = None
    PhoneOpenHours: Optional[str] = None
    Ean: Optional[str] = None
    Url: Optional[str] = None
    Landline: Optional[str] = None
    Post: Optional[str] = None
    PostSecondary: Optional[str] = None
    FOA: Optional[str] = None
    PNR: Optional[str] = None
    SOR: Optional[str] = None
    Tasks: Set[UUID] = set()
    ItSystems: Set[UUID] = set()
    ContactForTasks: Set[UUID] = set()
    ContactPlaces: Set[UUID] = set()


# User:
"""
    public class UserRegistration {
        public string Uuid;
        public string ShortKey;
        public string UserId;
        public string PhoneNumber;
        public string Landline;
        public string Email;
        public string RacfID;
        public string Location;
        public string FMKID;
        public List<Position> Positions;
        public Person Person;
        public DateTime Timestamp;
    }

    public class Position {
        public string Name;
        public string OrgUnitUuid;
        public string StartDate; // yyyy-MM-dd (or null)
        public string StopDate; // yyyy-MM-dd (or null)
    }
    public class Person {
        public string Name;
        public string Cpr;
    }
    """


class Person(BaseModel):
    Name: str
    Cpr: str | None = None


class Position(BaseModel):
    Name: str  # Job-function
    OrgUnitUuid: UUID
    # Not in use yet so always None:
    StartDate: date | None = None
    StopDate: date | None = None


class User(BaseModel):
    Uuid: UUID
    ShortKey: str | None = None  # Not in use so always None:
    UserId: str  # Username

    Person: Person
    Positions: list[Position]
    PhoneNumber: str | None = None
    Landline: str | None = None
    Email: str | None = None
    RacfID: str | None = None
    Location: str | None = None
    FMKID: str | None = None

    DateTime: datetime | None = None  # Registration time for os2sync - never set this


def convert_mo_to_fk_user(
    user: ReadUserItusersObjectsCurrent, settings: Settings
) -> User:
    assert user.person
    mo_person = one(user.person)
    person = Person(Name=mo_person.given_name, Cpr=mo_person.cpr_number)
    positions = [
        Position(Name=p.job_function.name, OrgUnitUuid=one(p.org_unit).uuid)
        for p in user.engagement or []
    ]
    landline = first(
        filter(
            lambda p: p.address_type.uuid in settings.landline_scope_classes, user.phone
        ),
        default=None,
    )

    mobile = first(
        filter(
            lambda p: p.address_type.uuid not in settings.landline_scope_classes,
            user.phone,
        ),
        default=None,
    )
    return User(
        Person=person,
        Positions=positions,
        Uuid=UUID(user.external_id),
        UserId=user.user_key,
        Email=x.value if (x := first(user.email, default=None)) is not None else None,
        Landline=landline.value if landline is not None else None,
        PhoneNumber=mobile.value if mobile is not None else None,
    )
