# Generated by ariadne-codegen on 2024-10-14 12:01
# Source: queries.graphql

from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class FindKLEUnit(BaseModel):
    itusers: "FindKLEUnitItusers"


class FindKLEUnitItusers(BaseModel):
    objects: List["FindKLEUnitItusersObjects"]


class FindKLEUnitItusersObjects(BaseModel):
    validities: List["FindKLEUnitItusersObjectsValidities"]


class FindKLEUnitItusersObjectsValidities(BaseModel):
    org_unit: Optional[List["FindKLEUnitItusersObjectsValiditiesOrgUnit"]]


class FindKLEUnitItusersObjectsValiditiesOrgUnit(BaseModel):
    uuid: UUID


FindKLEUnit.update_forward_refs()
FindKLEUnitItusers.update_forward_refs()
FindKLEUnitItusersObjects.update_forward_refs()
FindKLEUnitItusersObjectsValidities.update_forward_refs()
FindKLEUnitItusersObjectsValiditiesOrgUnit.update_forward_refs()
