# Generated by ariadne-codegen on 2024-10-01 11:16
# Source: queries.graphql

from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class OrgUnitPlacement(BaseModel):
    current: Optional["OrgUnitPlacementCurrent"]


class OrgUnitPlacementCurrent(BaseModel):
    uuid: UUID
    ancestors: List["OrgUnitPlacementCurrentAncestors"]
    unit_type: Optional["OrgUnitPlacementCurrentUnitType"]
    org_unit_level: Optional["OrgUnitPlacementCurrentOrgUnitLevel"]
    org_unit_hierarchy_model: Optional["OrgUnitPlacementCurrentOrgUnitHierarchyModel"]


class OrgUnitPlacementCurrentAncestors(BaseModel):
    uuid: UUID


class OrgUnitPlacementCurrentUnitType(BaseModel):
    uuid: UUID


class OrgUnitPlacementCurrentOrgUnitLevel(BaseModel):
    uuid: UUID


class OrgUnitPlacementCurrentOrgUnitHierarchyModel(BaseModel):
    name: str


OrgUnitPlacement.update_forward_refs()
OrgUnitPlacementCurrent.update_forward_refs()
OrgUnitPlacementCurrentAncestors.update_forward_refs()
OrgUnitPlacementCurrentUnitType.update_forward_refs()
OrgUnitPlacementCurrentOrgUnitLevel.update_forward_refs()
OrgUnitPlacementCurrentOrgUnitHierarchyModel.update_forward_refs()
