# Generated by ariadne-codegen on 2024-09-06 13:59
# Source: queries.graphql
from typing import List
from uuid import UUID

from .base_model import BaseModel


class GetEngagement(BaseModel):
    engagements: List["GetEngagementEngagements"]


class GetEngagementEngagements(BaseModel):
    objects: List["GetEngagementEngagementsObjects"]


class GetEngagementEngagementsObjects(BaseModel):
    employee_uuid: UUID


GetEngagement.update_forward_refs()
GetEngagementEngagements.update_forward_refs()
GetEngagementEngagementsObjects.update_forward_refs()
