# Generated by ariadne-codegen on 2024-09-06 13:59
# Source: queries.graphql
from datetime import datetime
from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class GetITAccountEnddate(BaseModel):
    itusers: List["GetITAccountEnddateItusers"]


class GetITAccountEnddateItusers(BaseModel):
    objects: List["GetITAccountEnddateItusersObjects"]


class GetITAccountEnddateItusersObjects(BaseModel):
    employee_uuid: Optional[UUID]
    org_unit_uuid: Optional[UUID]
    user_key: str
    itsystem: "GetITAccountEnddateItusersObjectsItsystem"
    validity: "GetITAccountEnddateItusersObjectsValidity"


class GetITAccountEnddateItusersObjectsItsystem(BaseModel):
    name: str


class GetITAccountEnddateItusersObjectsValidity(BaseModel):
    to: Optional[datetime]


GetITAccountEnddate.update_forward_refs()
GetITAccountEnddateItusers.update_forward_refs()
GetITAccountEnddateItusersObjects.update_forward_refs()
GetITAccountEnddateItusersObjectsItsystem.update_forward_refs()
GetITAccountEnddateItusersObjectsValidity.update_forward_refs()
