# Generated by ariadne-codegen on 2024-09-06 13:59
# Source: queries.graphql
from typing import List
from uuid import UUID

from .base_model import BaseModel


class GetManager(BaseModel):
    managers: List["GetManagerManagers"]


class GetManagerManagers(BaseModel):
    objects: List["GetManagerManagersObjects"]


class GetManagerManagersObjects(BaseModel):
    org_unit_uuid: UUID


GetManager.update_forward_refs()
GetManagerManagers.update_forward_refs()
GetManagerManagersObjects.update_forward_refs()
