# Generated by ariadne-codegen on 2024-09-06 13:59
# Source: queries.graphql
from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class GetAddress(BaseModel):
    addresses: List["GetAddressAddresses"]


class GetAddressAddresses(BaseModel):
    objects: List["GetAddressAddressesObjects"]


class GetAddressAddressesObjects(BaseModel):
    employee_uuid: Optional[UUID]
    org_unit_uuid: Optional[UUID]


GetAddress.update_forward_refs()
GetAddressAddresses.update_forward_refs()
GetAddressAddressesObjects.update_forward_refs()
