# Generated by ariadne-codegen on 2024-09-06 13:59
# Source: queries.graphql
from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class GetFKOrgUserMap(BaseModel):
    itusers: List["GetFKOrgUserMapItusers"]


class GetFKOrgUserMapItusers(BaseModel):
    current: Optional["GetFKOrgUserMapItusersCurrent"]


class GetFKOrgUserMapItusersCurrent(BaseModel):
    person: Optional[List["GetFKOrgUserMapItusersCurrentPerson"]]
    user_key: str
    itsystem: "GetFKOrgUserMapItusersCurrentItsystem"


class GetFKOrgUserMapItusersCurrentPerson(BaseModel):
    uuid: UUID


class GetFKOrgUserMapItusersCurrentItsystem(BaseModel):
    name: str


GetFKOrgUserMap.update_forward_refs()
GetFKOrgUserMapItusers.update_forward_refs()
GetFKOrgUserMapItusersCurrent.update_forward_refs()
GetFKOrgUserMapItusersCurrentPerson.update_forward_refs()
GetFKOrgUserMapItusersCurrentItsystem.update_forward_refs()
