# Generated by ariadne-codegen on 2024-10-25 09:25
# Source: queries.graphql

from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class LocateFKUser(BaseModel):
    itusers: "LocateFKUserItusers"
    employees: "LocateFKUserEmployees"


class LocateFKUserItusers(BaseModel):
    objects: List["LocateFKUserItusersObjects"]


class LocateFKUserItusersObjects(BaseModel):
    current: Optional["LocateFKUserItusersObjectsCurrent"]


class LocateFKUserItusersObjectsCurrent(BaseModel):
    person: Optional[List["LocateFKUserItusersObjectsCurrentPerson"]]


class LocateFKUserItusersObjectsCurrentPerson(BaseModel):
    engagements: List["LocateFKUserItusersObjectsCurrentPersonEngagements"]


class LocateFKUserItusersObjectsCurrentPersonEngagements(BaseModel):
    uuid: UUID


class LocateFKUserEmployees(BaseModel):
    objects: List["LocateFKUserEmployeesObjects"]


class LocateFKUserEmployeesObjects(BaseModel):
    current: Optional["LocateFKUserEmployeesObjectsCurrent"]


class LocateFKUserEmployeesObjectsCurrent(BaseModel):
    engagements: List["LocateFKUserEmployeesObjectsCurrentEngagements"]


class LocateFKUserEmployeesObjectsCurrentEngagements(BaseModel):
    uuid: UUID


LocateFKUser.update_forward_refs()
LocateFKUserItusers.update_forward_refs()
LocateFKUserItusersObjects.update_forward_refs()
LocateFKUserItusersObjectsCurrent.update_forward_refs()
LocateFKUserItusersObjectsCurrentPerson.update_forward_refs()
LocateFKUserItusersObjectsCurrentPersonEngagements.update_forward_refs()
LocateFKUserEmployees.update_forward_refs()
LocateFKUserEmployeesObjects.update_forward_refs()
LocateFKUserEmployeesObjectsCurrent.update_forward_refs()
LocateFKUserEmployeesObjectsCurrentEngagements.update_forward_refs()
