# Generated by ariadne-codegen on 2024-09-06 13:59
# Source: queries.graphql
from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class QueryEmployees(BaseModel):
    engagements: List["QueryEmployeesEngagements"]


class QueryEmployeesEngagements(BaseModel):
    current: Optional["QueryEmployeesEngagementsCurrent"]


class QueryEmployeesEngagementsCurrent(BaseModel):
    person: List["QueryEmployeesEngagementsCurrentPerson"]


class QueryEmployeesEngagementsCurrentPerson(BaseModel):
    uuid: UUID


QueryEmployees.update_forward_refs()
QueryEmployeesEngagements.update_forward_refs()
QueryEmployeesEngagementsCurrent.update_forward_refs()
QueryEmployeesEngagementsCurrentPerson.update_forward_refs()
