# Generated by ariadne-codegen on 2024-09-06 13:59
# Source: queries.graphql
from typing import List
from typing import Optional
from uuid import UUID

from .base_model import BaseModel


class QueryAncestors(BaseModel):
    org_units: List["QueryAncestorsOrgUnits"]


class QueryAncestorsOrgUnits(BaseModel):
    current: Optional["QueryAncestorsOrgUnitsCurrent"]


class QueryAncestorsOrgUnitsCurrent(BaseModel):
    ancestors: List["QueryAncestorsOrgUnitsCurrentAncestors"]
    org_unit_hierarchy_model: Optional[
        "QueryAncestorsOrgUnitsCurrentOrgUnitHierarchyModel"
    ]
    itusers: List["QueryAncestorsOrgUnitsCurrentItusers"]


class QueryAncestorsOrgUnitsCurrentAncestors(BaseModel):
    uuid: UUID


class QueryAncestorsOrgUnitsCurrentOrgUnitHierarchyModel(BaseModel):
    name: str


class QueryAncestorsOrgUnitsCurrentItusers(BaseModel):
    itsystem: "QueryAncestorsOrgUnitsCurrentItusersItsystem"


class QueryAncestorsOrgUnitsCurrentItusersItsystem(BaseModel):
    name: str


QueryAncestors.update_forward_refs()
QueryAncestorsOrgUnits.update_forward_refs()
QueryAncestorsOrgUnitsCurrent.update_forward_refs()
QueryAncestorsOrgUnitsCurrentAncestors.update_forward_refs()
QueryAncestorsOrgUnitsCurrentOrgUnitHierarchyModel.update_forward_refs()
QueryAncestorsOrgUnitsCurrentItusers.update_forward_refs()
QueryAncestorsOrgUnitsCurrentItusersItsystem.update_forward_refs()
