# Generated by ariadne-codegen on 2025-09-15 12:06
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class TerminateITUser(BaseModel):
    ituser_terminate: "TerminateITUserItuserTerminate"


class TerminateITUserItuserTerminate(BaseModel):
    uuid: UUID


TerminateITUser.update_forward_refs()
TerminateITUserItuserTerminate.update_forward_refs()
