# Generated by ariadne-codegen on 2025-09-15 08:34
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class TestingEngagementCreate(BaseModel):
    engagement_create: "TestingEngagementCreateEngagementCreate"


class TestingEngagementCreateEngagementCreate(BaseModel):
    uuid: UUID


TestingEngagementCreate.update_forward_refs()
TestingEngagementCreateEngagementCreate.update_forward_refs()
