# Generated by ariadne-codegen on 2025-09-05 14:36
# Source: queries.graphql

from typing import List
from uuid import UUID

from .base_model import BaseModel


class TestGetClass(BaseModel):
    classes: "TestGetClassClasses"


class TestGetClassClasses(BaseModel):
    objects: List["TestGetClassClassesObjects"]


class TestGetClassClassesObjects(BaseModel):
    uuid: UUID


TestGetClass.update_forward_refs()
TestGetClassClasses.update_forward_refs()
TestGetClassClassesObjects.update_forward_refs()
