# Generated by ariadne-codegen on 2024-11-13 08:25
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class UpdateItUserUserKey(BaseModel):
    ituser_update: "UpdateItUserUserKeyItuserUpdate"


class UpdateItUserUserKeyItuserUpdate(BaseModel):
    uuid: UUID


UpdateItUserUserKey.update_forward_refs()
UpdateItUserUserKeyItuserUpdate.update_forward_refs()
